services:
    airflow:
        build:
            context: .
            dockerfile: Dockerfile.airflow
        container_name: airflow
        ports:
            - "8080:8080"
        volumes:
            - ./dags:/app/dags
            - ./tmp:/tmp
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - AIRFLOW__CORE__LOAD_EXAMPLES=False
        networks:
            - app_network
        command: >
            bash -c "airflow db migrate && sleep 5 && airflow users create --username admin --firstname cho --lastname sungsu --role Admin --email ski06043@gmail.com --password 1234 && airflow webserver & airflow scheduler"

    mlflow:
        build:
            context: .
            dockerfile: Dockerfile.mlflow
        ports:
            - "5001:5000"
        volumes:
            - ./mlflow:/mlflow
            - ./mlartifacts:/mlartifacts
        environment:
            - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
            - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow/db/mlflow.db
        command: >
            mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlartifacts --host 0.0.0.0 --port 5000
        networks:
            - app_network

    spotify_api:
        build:
            context: .
            dockerfile: Dockerfile.spotify_api
        container_name: spotify_api
        volumes:
            - ./dags/data:/app/dags/data
        environment:
            - SPOTIFY_CLIENT_ID=50c56657aabf40399a6bc9fc664efc82
            - SPOTIFY_CLIENT_SECRET=6570994a38604701a26074800c9b6045
            - SPOTIFY_REDIRECT_URI=http://localhost:8000/callback
        command: >
            /bin/bash -c "while true; do sleep 1; done"
        networks:
            - app_network

    fastapi:
        build:
            context: .
            dockerfile: Dockerfile.fastapi
        container_name: fastapi
        ports:
            - "8000:8000"
        volumes:
            - ./dags:/app/dags
        environment:
            - SPOTIFY_CLIENT_ID=50c56657aabf40399a6bc9fc664efc82
            - SPOTIFY_CLIENT_SECRET=6570994a38604701a26074800c9b6045

        command: >
            uvicorn app:app --host 0.0.0.0 --port 8000
        networks:
            - app_network

    streamlit:
        build:
            context: .
            dockerfile: Dockerfile.streamlit
        container_name: streamlit
        ports:
            - "8501:8501"
        volumes:
            - ./dags:/app/dags
        depends_on:
            - fastapi
        command: >
            streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
# docker-compose build
# docker-compose up
# docker-compose exec airflow bash
# docker-compose exec mlflow bash

# 권한문제 해결 > chmod -R 777 ./dags/
