FROM python:3.10-slim

# 환경 변수 설정
ENV FastAPI_HOME=/app

# 필요한 패키지 및 의존성 설치
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# 작업 디렉토리 설정
WORKDIR $FastAPI_HOME

# Python 패키지 설치
COPY ./requirements.txt $FastAPI_HOME/
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# FastAPI 코드와 모델 관련 파일 복사
COPY ./dags/ $FastAPI_HOME/dags/
COPY ./app.py $FastAPI_HOME/

# Uvicorn을 사용해 FastAPI 서버 실행
# CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]